apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-service-config
  namespace: apps
  labels:
    app.kubernetes.io/name: inventory-service
    app.kubernetes.io/part-of: order-fulfillment
data:
  PORT: "8082"
