apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-config
  namespace: apps
  labels:
    app.kubernetes.io/name: worker
    app.kubernetes.io/part-of: order-fulfillment
data:
  HEALTH_PORT: "8090"
  SQS_QUEUE_URL: "https://sqs.eu-west-2.amazonaws.com/767398132018/eks-v2-sqs-queue"
  ORDER_SERVICE_URL: "http://order-service:8081"
  INVENTORY_SERVICE_URL: "http://inventory-service:8082"
  PAYMENT_SERVICE_URL: "http://payment-service:8083"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8084"
  SHIPPING_SERVICE_URL: "http://shipping-service:8085"
