apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: apps
  labels:
    app.kubernetes.io/name: worker
    app.kubernetes.io/part-of: order-fulfillment
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: worker
  ports:
    - name: health
      port: 8090
      targetPort: health
