apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  namespace: apps
  labels:
    app.kubernetes.io/name: shipping-service
    app.kubernetes.io/part-of: order-fulfillment
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: shipping-service
  ports:
    - name: http
      port: 8085
      targetPort: http
