apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: apps
  labels:
    app.kubernetes.io/name: payment-service
    app.kubernetes.io/part-of: order-fulfillment
data:
  PORT: "8083"
  SQS_QUEUE_URL: "https://sqs.eu-west-2.amazonaws.com/767398132018/eks-v2-sqs-queue"
