apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-service
  namespace: apps
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::767398132018:role/eks-v2-sqs-producer
  labels:
    app.kubernetes.io/name: payment-service
    app.kubernetes.io/part-of: order-fulfillment
