apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: apps
  labels:
    app.kubernetes.io/name: payment-service
    app.kubernetes.io/part-of: order-fulfillment
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: payment-service
  ports:
    - name: http
      port: 8083
      targetPort: http
