apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-platform-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: order-platform
  source:
    repoURL: https://github.com/Mo-ASayed/eks-order-platform-v2.git
    targetRevision: main
    path: Kubernetes/apps/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: apps-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  revisionHistoryLimit: 10
